public enum PacketType : ushort
{
    // login 100
    C_Login    = 100,
    S_Login    = 101,
    C_Register = 102,
    S_Register = 103,

    // poker 200
    C_GetRoomList        = 200,
    S_GetRoomList        = 201,
    C_CreateRoom         = 202,
    S_CreateRoom         = 203,
    C_JoinRoom           = 204,
    S_JoinRoom           = 205,
    C_LeaveRoom          = 206,
    S_LeaveRoom          = 207,
    C_StartGame          = 208,
    S_StartGame          = 209,
    C_BetAction          = 210,
    S_BetTurn            = 211,
    S_BetResult          = 212,
    S_OpenCommunityCards = 213,
    S_GameResult         = 214,
    S_Notice             = 215,
    C_BattleRequest          = 216,
    S_BattleIncoming         = 217,
    C_BattleAccept           = 218,
    C_BattleReject           = 219,
    S_BattleAccepted         = 220,
    S_BattleEnter            = 223,

    // UDP — 로비 동기화 300
    C_UdpHello            = 300,
    C_LobbyMove           = 301,
    C_LobbyHeartbeat      = 302,
    C_BuyWeapon           = 303,
    C_BattleEnter         = 304,
    S_UdpHandshakeAck     = 350,
    S_LobbyPlayerMove     = 352,
    S_LobbyPlayerLeave    = 353,
    S_PlayerInfo          = 354,
    S_BuyWeaponResult     = 355,
    S_BattleEnterResult   = 356,
}
